### ISSUE TITLE
info-tabs background and scrollbar (Zotero 5.0.97 beta.43) 

### ISSUE THREAD

**Issue by jorjio** [Rosmaninho/Zotero-Dark-Theme#10]
Thank you for this beautiful work!!
I have two issues: 
The info tabs background is bright colored:
![zotero_JTmH1yLYUz](https://user-images.githubusercontent.com/5610394/132910893-9f18a234-8f36-47ef-a727-2d86de044ecd.png)

and would appreciate if you could change scrollbars color to dark as well.

Thanks so much for your efforts and all the best!

**Comment by Rosmaninho** [comment]
Scrollbars can't be changed via userChrome.css and making an userContent.css file to change it like for Firefox doesn't do anything so I can't change them.
I suppose you are on the 5.0.97 Beta? That white color appeared to me randomly, but when I closed it and opened it again it was back to dark so not entirely sure what's happening. I'll check it once 5.0.97 hits release ok?

**Comment by jorjio** [comment]
Thanks so much!

**Comment by rknx** [comment]
Please check this. #15 

Basically, what you want is to add:
`#zotero-item-pane-content {background: #323234 !important; }`

**Comment by jorjio** [comment]
Amazing! Thanks so much!

**Comment by jorjio** [comment]
@rknx, any chance you know how to change the background to the "Load Items" screen that appears when you open Zotero?

**Comment by rknx** [comment]
I'm not exactly sure about a "load items" screen. I will try to look into it after the weekend, but you can leave a screenshot for me or @Rosmaninho to diagnose.

**Comment by jorjio** [comment]
please see screenshot..Thanks.
<img width="960" alt="zM0soOVEeA" src="https://user-images.githubusercontent.com/5610394/141608983-43421587-4d7c-4dc0-bb0d-de0d1a79ca30.png">

**Comment by rknx** [comment]
@jorjio try adding this:
`#zotero-items-tree {color: #ffffff; background: #323234 !important; }`

**Comment by jorjio** [comment]
Great Stuff @rknx !!!

**Comment by actforjason** [comment]
dark scrollbar：
https://github.com/Dominic-DallOsto/Zotero-Dark-Theme
