### ISSUE TITLE
static pane navigator background color

### ISSUE THREAD

**Issue by zareshahi** [Rosmaninho/Zotero-Dark-Theme#14]
Hey, Thanks for designing this CSS file and this application method for Zotero
hope Zotero use your try in their future versions

I use Zotero pre-released  5.0.97 beta version and I was uncommented CSS styles about pre-released version
now I just have problem with static text panes like loading page or this empty page that just have text

![image](https://user-images.githubusercontent.com/7747315/137967925-202b7fd0-6e0a-434b-88b6-b4e7fe2bef52.png)

**Comment by rknx** [comment]
@zareshahi Can you please check if this fixes your issue? https://github.com/Rosmaninho/Zotero-Dark-Theme/issues/10#issuecomment-968468079

**Comment by zareshahi** [comment]
> @zareshahi Can you please check if this fixes your issue? [#10 (comment)](https://github.com/Rosmaninho/Zotero-Dark-Theme/issues/10#issuecomment-968468079)
 

> try adding this:
> `#zotero-items-tree {color: #ffffff; background: #323234 !important; }`

Thanks, It's a good solution and fixed the issue.
