### ISSUE TITLE
Notes are still white

### ISSUE THREAD

**Issue by happyTonakai** [Rosmaninho/Zotero-Dark-Theme#17]
Firstly I want to say thank you for the greate work!

I found that when I add a note for an item, it is still in white color. Could you fix it? Thanks!

![screenshot-20211116-094513](https://user-images.githubusercontent.com/21305646/141880721-f64f4ed3-d083-4157-9f67-65f3aed462e4.png)

I'm using Zotero 5.0.96.3 and the css theme file is also up to date.

**Comment by martinholub** [comment]
I am trying to find a way to fix this but no success so far. If anyone knows which `#tag` to change, please let us know

**Comment by rknx** [comment]
To the best of my knowledge, zotero uses tinymce for note editor.

You can find source for tinymce css [here](https://github.com/zotero/web-library/blob/master/src/scss/tinymce-content.scss).  
The colors for light theme are [here](https://github.com/zotero/web-library/blob/master/src/scss/themes/_light.scss).  
More related files may be [here](https://github.com/zotero/web-library/tree/master/src/scss/components/rich-editor) and [here](https://github.com/zotero/web-library/tree/master/src/scss/components/note).  

I don't exactly know how you can modify this (maybe in zotero.jar).

**Comment by zazench** [comment]
Hi everyone. I was looking for a solution to this and stumbled upon this [Zotero forum topic](https://forums.zotero.org/discussion/86855/make-note-editor-beautiful) where user **fbcx** posted some css to make the note editor more beautiful, and added in a [comment](https://forums.zotero.org/discussion/86855/make-note-editor-beautiful#Comment_372922) how to change the background color.
Full credit to user [fbcx](https://forums.zotero.org/profile/7296727/fbcx):

Here's the gist of it:
open Zotero, then

> 1. go to Preferences → Advanced → Config Editor
> 2. type in 'note'
> 3. double-click 'extensions.zotero.note.css'
> 4. paste the CSS (see bottom of this post) into the text field
> 5. click 'OK'

1. open Zotero
2. go to Preferences → Advanced → Config Editor
3. I accept the risks!
4. search `extensions.zotero.note.css` and double-click it
5. Insert the following string, an edited version of the one cited above
6. click 'OK'

```
body {
color: white;
max-width: 35em;
margin: 0 auto;
padding-left: 20px;
padding-right: 20px;
background-color: #474749;
}

h1 {
color: white;
font-size: 1.6em;
padding-bottom: none;
}

h2 {
color: white;
font-size: 1.4em;
font-weight: bold;
padding-bottom: none;
border-bottom: none;
}

h3 {
color: white;
font-size: 1.2em;
}

p {
text-indent: 1.75em;
}

ul,
ol {
padding-left: 1.75em;
}

blockquote {
margin-top: 0;
margin-bottom: 0;
margin-left: 0;
padding-left: 1.55em;
border-left: 3px solid darkgrey;
color: white (255, 248, 248);
}
blockquote p {
text-indent: 0;
}
```

8. Close and restart Zotero

Notice that:
- color for both body and headers text is set to _white_
- background-color is set to _#474749_, which is the shade chosen by Rosmaninho for this dark theme 
- the color of the line for blockquotes is set to _solid darkgrey_ to distinguish it from the background
You may change these parameters by setting a different color in the above .css script.

I hope this helps!

**Comment by Rosmaninho** [comment]
I'll add this to Main when I get the time to test it.

**Comment by zazench** [comment]
Sure, and thanks for your work.
I use all software with dark themes and it was a pain to switch to Zotero and get blinded every single time.
Cheers!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il martedì 23 novembre 2021 4:46 PM, Rosmaninho ***@***.***> ha scritto:

**Comment by sddpszz** [comment]
Thanks for your solution, but the beta version (`5.0.97-beta.57`) of notes is still white, any suggestions?

**Comment by Rosmaninho** [comment]
I tried to add the modifications mentioned above to the userChrome.css file but it produces no effects.
You need to follow the instruction of Zazench which are independent of the css file.

**Comment by sddpszz** [comment]
> I tried to add the modifications mentioned above to the userChrome.css file but it produces no effects. You need to follow the instruction of Zazench which are independent of the css file.

Yes, I've tried Zazench‘s solution, but it still doesn't work, and I see that the new note editor is mentioned on this [site: Available in Preview](https://www.zotero.org/support/pdf_reader_preview)

**Comment by Rosmaninho** [comment]
If it's on the Beta version it's a bit harder to make it work... As the name says, it's still in development so css modifications might break.

**Comment by 10cks** [comment]
> Hi everyone. I was looking for a solution to this and stumbled upon this [Zotero forum topic](https://forums.zotero.org/discussion/86855/make-note-editor-beautiful) where user **fbcx** posted a css snippet to make the note editor more beautiful, and added in a [comment](https://forums.zotero.org/discussion/86855/make-note-editor-beautiful#Comment_372922) how to change the background color. Full credit for the original snippet goes to user [fbcx](https://forums.zotero.org/profile/7296727/fbcx).
> 
> Here's the gist of it:
> 
> 1. open Zotero
> 2. go to Preferences → Advanced → Config Editor
> 3. I accept the risks!
> 4. search `extensions.zotero.note.css` and double-click it
> 5. Insert the following string, an edited version of the one cited above
> 6. click 'OK'
> 
> ```
> body {
> color: white;
> max-width: 35em;
> margin: 0 auto;
> padding-left: 20px;
> padding-right: 20px;
> background-color: #474749;
> }
> 
> h1 {
> color: white;
> font-size: 1.6em;
> padding-bottom: none;
> }
> 
> h2 {
> color: white;
> font-size: 1.4em;
> font-weight: bold;
> padding-bottom: none;
> border-bottom: none;
> }
> 
> h3 {
> color: white;
> font-size: 1.2em;
> }
> 
> p {
> text-indent: 1.75em;
> }
> 
> ul,
> ol {
> padding-left: 1.75em;
> }
> 
> blockquote {
> margin-top: 0;
> margin-bottom: 0;
> margin-left: 0;
> padding-left: 1.55em;
> border-left: 3px solid darkgrey;
> color: white (255, 248, 248);
> }
> blockquote p {
> text-indent: 0;
> }
> ```
> 
> 8. Close and restart Zotero
> 
> Notice that:
> 
> * color for both body and headers text is set to _white_
> * background-color is set to _#474749_, which is the shade chosen by Rosmaninho for this dark theme
> * the color of the line for blockquotes is set to _solid darkgrey_ to distinguish it from the background
>   You may change these parameters by setting a different color in the above .css snippet.
> 
> I hope this helps!

thanks for your help.It works.

**Comment by Rosmaninho** [comment]
I will add another section with your information for anyone who wants to theme the Note editor.

**Comment by FeralFlora** [comment]
@zazench's solution should work for Zotero 6 now.

**Comment by martinholub** [comment]
> @zazench's solution should work for Zotero 6 now.

It does not for me (Windows 10). The black theme otherwise works fine,
