### ISSUE TITLE
White collections pane and column headers

### ISSUE THREAD

**Issue by ClandestineClout** [Rosmaninho/Zotero-Dark-Theme#21]
I'm not sure what else there is to say. I'm on Zotero 5.0.97 beta. Is that possibly the reason?

**Comment by Rosmaninho** [comment]
I would say so, since I am not aiming towards the Beta (it's a constant moving goal post - I already have stuff prepared because a lot of people start opening issues because of it and to save me some work later to adjust).

**Comment by ClandestineClout** [comment]
I assume you're aware of this but in case anyone stumbles upon this, I was able to fix this issue for the time being by uncommenting the CSS lines to do with the pre-release (i.e. enabling the styling).
