### ISSUE TITLE
Does it work on windows 11?

### ISSUE THREAD

**Issue by WMAM** [Rosmaninho/Zotero-Dark-Theme#23]
Just that!

**Comment by Rosmaninho** [comment]
No idea. My PC is too old for Windows 11.

**Comment by WMAM** [comment]
Thank you! I asked because I created the folder "chrome" and copied there this CSS file, but nothing happen. 
The folder structure in W11 is pretty similar to W10, and I thought it had a chance to work... At least for me, it didn't

**Comment by Rosmaninho** [comment]
I'll leave the issue open so that more people can confirm this, and if someone can offer a solution. I'll try to get my hands onto a W11 notebook to test this but I can't promise a quick fix.

**Comment by WMAM** [comment]
Thank you so much!

**Comment by WMAM** [comment]
Then, I guess it would be a beta version issue.

**Comment by SoZoYo** [comment]
It worked for me on Windows 11 Home version 21H2.

I created a file named userChrome.css pasted the CSS and placed it in C:\Users\[username]\AppData\Roaming\Zotero\Zotero\Profiles\dtyiqzyg.default\chrome

Make sure you have the latest version of Zotero and that you named everything correctly?

**Comment by WMAM** [comment]
@SoZoYo Thank you so much for the information. It seems that my error was that I "downloaded" the CSS file, instead of copying and pasting its content to a local file.
It is now working with the Zotero-beta and Windows 11...  only the left pane (with library collections) remains in light mode. There is no big problem with that. What makes me unreadable is the selected item in the central panel (and the column headers), as it could be appreciated in this screenshot. Any idea how to correct it?
Thanks a lot for your help!

![imagen](https://user-images.githubusercontent.com/31582800/152296801-d6d35362-ff53-4643-88e0-4e20082ed5df.png)

**Comment by SoZoYo** [comment]
Sorry. I'm not on the beta version. The only thing that isn't dark for me is the note editor. I can only assume the beta has different selectors.

**Comment by AporiaYixara** [comment]
> only the left pane (with library collections) remains in light mode. There is no big problem with that. What makes me unreadable is the selected item in the central panel (and the column headers), as it could be appreciated in this screenshot. Any idea how to correct it? Thanks a lot for your help!
> 

When I opened the .CSS file I found blocks of code that are commented out. These are for the beta version. I uncommented them and it made several more areas Dark.

**Comment by WMAM** [comment]
@AporiaYixara Yes, thank you so much!!! It is working nice now.

**Comment by Rosmaninho** [comment]
Sorry for the delay in replying. Glad you found out the issue. It's hard to know when instructions are or are not clear enough.

**Comment by WMAM** [comment]
@Rosmaninho Don't worry, thank you very much for your work!
