### ISSUE TITLE
zotero has updated to 6.0, are there any plan to update this plugin to better adapt to the new version?

### ISSUE THREAD

**Issue by Xieleilab** [Rosmaninho/Zotero-Dark-Theme#27]

**Comment by Rosmaninho** [comment]
Yes, there are. No, I won't magically do this in the 2 hours after the new version is released because I am not stored in stasis just waiting for a new version of Zotero to launch to fix the theme.
I have a life outside of this. ;)

**Comment by Rosmaninho** [comment]
Updated userChrome.css. Try now.
