### ISSUE TITLE
The nine colored tags are displayed in white

### ISSUE THREAD

**Issue by CarlossShi** [Rosmaninho/Zotero-Dark-Theme#28]
First of all I want to thank you for your great work! I have a question about the display of colored tags.

As usual, the lower left panel for selecting tags will display their colors. But when I use the updated .css file in Zotero 6.0, they appear all in white. Below is an example before and after using the .css file.

![image](https://user-images.githubusercontent.com/50014508/159121511-8ea4e223-d729-4ab6-8f18-75747f27779d.png)

**Comment by Rosmaninho** [comment]
Okay, updated the userChrome.css file. Could you care to try it and tell me if it addressed your problem?

**Comment by CarlossShi** [comment]
It works, thanks!
