### ISSUE TITLE
Adding the theme to a Linux Flatpak?

### ISSUE THREAD

**Issue by edent** [Rosmaninho/Zotero-Dark-Theme#29]
Hello - I love the look of these theme. Do you know how I would install it on Linux?

I'm using the Flatpak version which seems to be located in `~/.var/app/org.zotero.Zotero` - but there's no `Profile` directory.

Any clue where I put it?

**Comment by Rosmaninho** [comment]
No idea where to put it, I haven't been exploring how flatpaks are structured.

**Comment by qoheniac** [comment]
The path is `~/.zotero/zotero/XXXXXXXX.default/chrome/userChrome.css`

**Comment by Rosmaninho** [comment]
Edent could you confirm if this is it?

**Comment by edent** [comment]
That works perfectly! I'll add it to the README.
