### ISSUE TITLE
Row spacing

### ISSUE THREAD

**Issue by joelnitta** [Rosmaninho/Zotero-Dark-Theme#3]
Thanks so much for this theme! In the absence of actual official support from Zotero, this is great.

I'm using the mac OS fork (https://github.com/quin-q/Zotero-Dark-Theme), so I'm not sure if this also applies to the main fork, but I can't file an issue over there.

I noticed that the row spacing is significantly larger with the dark theme vs. default. I prefer the narrow (default) row spacing. Is there any way to change this?

<img width="2455" alt="dark" src="https://user-images.githubusercontent.com/13459362/106073269-0fc6e080-614d-11eb-9e01-ebd692fadcba.png">

<img width="2455" alt="light" src="https://user-images.githubusercontent.com/13459362/106073300-21a88380-614d-11eb-8ba7-4c195e663075.png">

**Comment by taralloc** [comment]
Also happens on Windows 10

**Comment by bdelepine** [comment]
You may want to reduce the row spacing in the Collection Pane (left pane) too by commenting the line: https://github.com/Rosmaninho/Zotero-Dark-Theme/blob/05072687ee1b8219c14be61ab6fb75d05f111f5c/userChrome.css#L37

**Comment by joelnitta** [comment]
Thanks! I didn't change the commenting, but rather adjusted the height settings from `30px` to `20px` at two lines:

https://github.com/Rosmaninho/Zotero-Dark-Theme/blob/05072687ee1b8219c14be61ab6fb75d05f111f5c/userChrome.css#L37

```
#zotero-collections-tree treechildren::-moz-tree-row { height: 20px !important; }
```

https://github.com/Rosmaninho/Zotero-Dark-Theme/blob/05072687ee1b8219c14be61ab6fb75d05f111f5c/userChrome.css#L50

```
#zotero-items-tree treechildren::-moz-tree-row { height: 20px !important; }
```

That seems to set the spacing to approximately what it looks like in the default style.

**Comment by Rosmaninho** [comment]
Yes, I'm sorry for not replying earlier. The increased row spacing was my personal preference. I thought it was clear in the file that you had to change that but I'll try to make it clearer when I have time.
