### ISSUE TITLE
Theme is broken in Zotero 6.0

### ISSUE THREAD

**Issue by iGr33k** [Rosmaninho/Zotero-Dark-Theme#30]
Seems like some of the styles've changed with the new version, so using the theme results in the following:
![image](https://user-images.githubusercontent.com/36838572/159178569-896dbd49-a411-426e-a90c-5b18cff658ca.png)

**Comment by Rosmaninho** [comment]
Are you using the updated userChrome.css that I posted yesterday?

**Comment by iGr33k** [comment]
Just checked with the new version. Works like charm, thanks.
