### ISSUE TITLE
Element List still white

### ISSUE THREAD

**Issue by 2er0** [Rosmaninho/Zotero-Dark-Theme#34]
Hey, I was able to import the dark mode style CSS to Zotero on MacOS.
I discovered the following style issue with the elements in all collections.
If I select one or hover over it, everything is nicely readable.

Any ideas what to change? 
Sorry, I'm not familiar with the CSS classes used by Zotero - I did not look into that.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/16341653/159965780-a080d744-d0a0-4caa-a869-8ccf8b648b60.png">

**Comment by Rosmaninho** [comment]
In MacOS the theme was broken and plenty of the ids did not work. I believe there's a fork that found some of the issues. 
Since I can't test on MacOS I really am not qualified to provide support.

**Comment by 2er0** [comment]
Which fork do you mean?

**Comment by Rosmaninho** [comment]
https://github.com/Rosmaninho/Zotero-Dark-Theme/issues/1 You can catch up on that issue.

**Comment by Rosmaninho** [comment]
https://github.com/yiktungho/Zotero-Dark-Theme/tree/mac-patch There you go. Hope it helps.
