### ISSUE TITLE
Can't see clicked item clearly

### ISSUE THREAD

**Issue by zxdawn** [Rosmaninho/Zotero-Dark-Theme#35]
If I click one item and move the mouse to another one, the gray color of the clicked item is hard to see:

![image](https://user-images.githubusercontent.com/30388627/160387264-3cdf6840-cb20-48a9-bdd7-51dd4a55baac.png)

However, the item where the mouse is over looks nice.
![image](https://user-images.githubusercontent.com/30388627/160387375-80b6c4ce-61dd-4030-b2b1-d93605a00680.png)

Do you know where to edit the color to make it looks better?

**Comment by Rosmaninho** [comment]
Weird. In my end it's looking good.
And in the .css file it is correct. Go to line 125 and you see that selected color is white. On line 121 hover color is white.
Are you using Windows? If not, that might explain it.

**Comment by zxdawn** [comment]
Ha, I'm using elementary os which is based on ubuntu. The default bright theme also doesn't work for this case (the hover color looks white).

**Comment by zxdawn** [comment]
Because this shouldn't be an issue of the dark theme, I submitted it on [Zotero forum](https://forums.zotero.org/discussion/95771/hover-color-doesnt-work-for-linux#latest).
