### ISSUE TITLE
contrast on items

### ISSUE THREAD

**Issue by fangzhou-xie** [Rosmaninho/Zotero-Dark-Theme#37]
Thank you very much for this dark theme! But I encounter the following situation where the items within the collection was barely visible.
<img width="848" alt="zotero" src="https://user-images.githubusercontent.com/45321577/161106257-45b2a782-3bcc-4e6e-b925-12e1e5cc6232.png">

I tried to search the other issues but didn't find anything related to this. 

Info: I am on macOS 11.6 Big Sur with Zotero 6.0.4.

**Comment by Rosmaninho** [comment]
I don't support MacOS since I don't have a Mac and I can't do nothing about it. 
You should check this fork from yiktungho for dark theme for MacOS:
https://github.com/yiktungho/Zotero-Dark-Theme/tree/mac-patch
