### ISSUE TITLE
Highlighting folders containing a source doesn't show

### ISSUE THREAD

**Issue by glocalglocal** [Rosmaninho/Zotero-Dark-Theme#40]
Selecting a source in the middle pane and pressing ctrl normally highlights in yellow the folders containing that source. This highlighting doesn't show. As far as I know there is no other way to locate the folders.

**Comment by Rosmaninho** [comment]
I wasn't aware of this functionality. I'll see if I can find a way to fix this.

**Comment by Rosmaninho** [comment]
Would you care to download the latest version of the userChrome.css and see if it fixes your issue?

**Comment by glocalglocal** [comment]
That works! Many thanks.
