### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Arcticwzh** [Rosmaninho/Zotero-Dark-Theme#43]
1. 标签面板：原本选中的标签周围有蓝色底色，现在都变成黑色了，导致选中的标签与未选中的标签没有视觉上的区别
2. 高级动态搜索：高级动态搜索保存结果的动态文件夹里面，原本符合搜索条件的条目是黑色字，其他条目是灰色字。现在都变成黑色了，看不出区别

感谢开发者的贡献！

**Comment by CharlesChiuGit** [comment]
Try to use ENGLISH.

**Comment by Rosmaninho** [comment]
I cannot replicate the issue in my installation. Are you using this in Windows?

**Comment by Arcticwzh** [comment]
Yes



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月21日(周四) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Rosmaninho/Zotero-Dark-Theme] 小问题 (Issue #43)




 
I cannot replicate the issue in my installation. Are you using this in Windows?

**Comment by Arcticwzh** [comment]
hello！
Tab panel: originally there was a blue background around the selected tabs, but now they have all become black, resulting in no visual difference between the selected tabs and the unselected ones.
This is an example video:
https://user-images.githubusercontent.com/100276333/164735742-a0d23070-c46f-4049-87ad-dd833647355b.mp4

**Comment by Rosmaninho** [comment]
Aaaaah! Now I understand what you mean! Those are TAGS, not tabs.

**Comment by Arcticwzh** [comment]
> 啊啊！现在我明白你的意思了！这些是标签，而不是标签。

Sry! And thank you for your Patient.
Can you solve this problem?

**Comment by Arcticwzh** [comment]
> 啊啊！现在我明白你的意思了！这些是标签，而不是标签。

Sorry！And thank you for your patience！
Can you solve this problem？

**Comment by Rosmaninho** [comment]
Please confirm fix.

**Comment by Arcticwzh** [comment]
> 请确认修复。

The problem is very perfect repaired
This is the first time my feedback to the developer has been accepted. 
Thank you very much for your work！

**Comment by Rosmaninho** [comment]
It was good feedback. :)
