### ISSUE TITLE
Can this css file work for the background in papers?

### ISSUE THREAD

**Issue by alexluo-netizen** [Rosmaninho/Zotero-Dark-Theme#47]
I followed the steps and it worked. But only the background of zotero is changed into black. The background of paper is still white.
Is it possible to change that as well?

**Comment by Rosmaninho** [comment]
That goes well beyond the purpose of this .css style sheet. But Thomas FK Jorna made an addon based on my .css that addresses that.

You can get it here:
https://github.com/tefkah/zotero-night
