### ISSUE TITLE
Buggy colors in config menus

### ISSUE THREAD

**Issue by mawright** [Rosmaninho/Zotero-Dark-Theme#50]
I'm running Ubuntu 22.04 with its built-in dark theme. There are a few graphical glitches in the config menus. Here are a couple examples that I think capture all of the element types:
![Screenshot from 2022-08-12 16-03-28](https://user-images.githubusercontent.com/2333858/184455339-08872faa-bec3-4b38-815a-d19d70bb78ad.png)
![Screenshot from 2022-08-12 16-03-35](https://user-images.githubusercontent.com/2333858/184455346-e652deed-89bb-4e46-8845-60c9b6445e3d.png)

Great theme, by the way. Really helps make Zotero easier to work with.

**Comment by Rosmaninho** [comment]
You can disable that portion of the userChrome.css. It was a pain to theme them and they are just barely decent IMO.
