### ISSUE TITLE
Zotero dark mode not working in Zotero 6 editor

### ISSUE THREAD

**Issue by MAN6O** [Rosmaninho/Zotero-Dark-Theme#52]
Hi,
 I have tried to change the theme by following your steps. I changed the note.css string to the string in the text file and also changed the editor.use.css varable from false to true, but its still the ugly light theme after restarting.

Best wishes

**Comment by Rosmaninho** [comment]
Unfortunately it does not work with the new editor from Zotero 6. That requires javascript to change. There's an addon that changes it though.
